### ISSUE TITLE
install not working

### ISSUE THREAD

**Issue by wayneseymour** [krusty-krab/minijasminenodewrap#6]
Hey bro, the install is not working per:
[our install instructions](https://github.com/krusty-krab/minijasminenodewrap/blob/master/readme.md#install)  
I had to do it like this: `$ npm install minijasminenodewrap@0.0.5 --save` _specific version_

**Comment by wayneseymour** [comment]
Seems to be working now after I spoke with @jgrund and he mentioned `$ npm cache clean`.

**Comment by johnsonw** [comment]
Hey bro, sorry I totally forgot to update the instructions :) I'm adding a
logger and updating the tests such that they have one expect per it.
